name       : python-simplegeneric
version    : 0.8.1
release    : 2
source     :
    - https://pypi.python.org/packages/3d/57/4d9c9e3ae9a255cd4e1106bb57e24056d3d0709fc01b2e3e345898e49d5b/simplegeneric-0.8.1.zip : dc972e06094b9af5b855b3df4a646395e43d1c9d0d39ed345b7393560d0b9173
license    : ZPL-2.1
component  : programming.python
summary    : Simple generic functions (similar to Python's own len(), pickle.dump(), etc.)
description: |
    The simplegeneric module lets you define simple single-dispatch generic functions, akin to Python's built-in generic functions like len(), iter() and so on. However, instead of using specially-named methods, these generic functions use simple lookup tables, akin to those used by e.g. pickle.dump() and other generic functions found in the Python standard library.
builddeps  :
    - pkgconfig(python3)
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
